'use client';

import { useState, useEffect } from 'react';
import { getReports } from '@smarthealth/api-client';
import { SymptomReport } from '@smarthealth/types';
import { FileText, Download, FileSpreadsheet, FileJson, File, CheckCircle2 } from 'lucide-react';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import { toast } from 'sonner';

export default function ReportsPage() {
  const [reports, setReports] = useState<SymptomReport[]>([]);
  const [isExporting, setIsExporting] = useState<string | null>(null);

  useEffect(() => {
    getReports().then(res => setReports(res as SymptomReport[]));
  }, []);

  const exportJSON = () => {
    setIsExporting('JSON');
    setTimeout(() => {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reports, null, 2));
      const downloadAnchorNode = document.createElement('a');
      downloadAnchorNode.setAttribute("href", dataStr);
      downloadAnchorNode.setAttribute("download", `smarthealth_export_${new Date().toISOString().split('T')[0]}.json`);
      document.body.appendChild(downloadAnchorNode);
      downloadAnchorNode.click();
      downloadAnchorNode.remove();
      setIsExporting(null);
      toast.success('JSON export completed successfully.');
    }, 800);
  };

  const exportCSV = () => {
    setIsExporting('CSV');
    setTimeout(() => {
      const worksheet = XLSX.utils.json_to_sheet(reports.map(r => ({
        ID: r.id,
        Village: r.villageId,
        Disease: r.diseaseType,
        Risk: r.outcome,
        Symptoms: r.symptoms.join(', '),
        Age: r.patientAge,
        Gender: r.patientGender,
        Time: r.timestamp
      })));
      const csv = XLSX.utils.sheet_to_csv(worksheet);
      const dataStr = "data:text/csv;charset=utf-8," + encodeURIComponent(csv);
      const downloadAnchorNode = document.createElement('a');
      downloadAnchorNode.setAttribute("href", dataStr);
      downloadAnchorNode.setAttribute("download", `smarthealth_export_${new Date().toISOString().split('T')[0]}.csv`);
      document.body.appendChild(downloadAnchorNode);
      downloadAnchorNode.click();
      downloadAnchorNode.remove();
      setIsExporting(null);
      toast.success('CSV export completed successfully.');
    }, 800);
  };

  const exportExcel = () => {
    setIsExporting('EXCEL');
    setTimeout(() => {
      const worksheet = XLSX.utils.json_to_sheet(reports.map(r => ({
        ID: r.id,
        Village: r.villageId,
        Disease: r.diseaseType,
        Risk: r.outcome,
        Symptoms: r.symptoms.join(', '),
        Age: r.patientAge,
        Gender: r.patientGender,
        Time: r.timestamp
      })));
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, "Symptom Reports");
      XLSX.writeFile(workbook, `smarthealth_export_${new Date().toISOString().split('T')[0]}.xlsx`);
      setIsExporting(null);
      toast.success('Excel export completed successfully.');
    }, 1200);
  };

  const exportPDF = () => {
    setIsExporting('PDF');
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(22);
      doc.setTextColor(15, 23, 42); // slate-900
      doc.text("SmartHealth Governance Bulletin", 20, 20);
      
      // Subtitle
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139); // slate-500
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 30);
      
      // Metrics Summary
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text("Executive Summary", 20, 45);
      
      doc.setFontSize(12);
      doc.setTextColor(71, 85, 105);
      const totalReports = reports.length;
      const redAlerts = reports.filter(r => r.outcome === 'RED').length;
      const amberAlerts = reports.filter(r => r.outcome === 'AMBER').length;
      
      doc.text(`Total Field Telemetry Logs (30 days): ${totalReports}`, 20, 55);
      doc.text(`Critical (RED) Alerts: ${redAlerts}`, 20, 65);
      doc.text(`Warning (AMBER) Alerts: ${amberAlerts}`, 20, 75);
      
      // Top Risk Clusters
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text("Top Risk Clusters (Active Outbreaks)", 20, 95);
      
      doc.setFontSize(12);
      doc.setTextColor(220, 38, 38); // red-600
      doc.text("1. Kipeto (v-101) - Cholera Anomaly Detected", 20, 105);
      doc.text("2. Bonde (v-105) - Dengue Cluster Identified", 20, 115);
      
      // Resource Status
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text("Resource Allocation Status", 20, 135);
      
      doc.setFontSize(12);
      doc.setTextColor(71, 85, 105);
      doc.text("Kipeto PHC: Critically Low ORS (<50 units)", 20, 145);
      doc.text("Bonde PHC: Critically Low IV Fluids (<50 units)", 20, 155);

      // Footer
      doc.setFontSize(10);
      doc.text("Generated by SmartHealth Automated Reporting Engine", 20, 280);

      doc.save(`smarthealth_bulletin_${new Date().toISOString().split('T')[0]}.pdf`);
      setIsExporting(null);
      toast.success('PDF Bulletin generated successfully.');
    }, 1500);
  };

  return (
    <div className="flex flex-col h-full gap-6">
      <div className="mb-2">
        <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">Governance & Compliance Reports</h1>
        <p className="text-sm text-slate-500 mt-1">Generate official bulletins and export raw data for external auditing.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* PDF Generator */}
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 flex flex-col items-center text-center hover:border-emerald-300 transition-colors">
          <div className="w-12 h-12 bg-red-50 text-red-600 rounded-full flex items-center justify-center mb-4">
            <FileText className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800 text-lg mb-2">PDF Bulletin</h3>
          <p className="text-xs text-slate-500 mb-6 flex-1">Executive summary containing map states, anomalies, and resource metrics.</p>
          <button 
            onClick={exportPDF}
            disabled={isExporting !== null}
            className="w-full flex items-center justify-center gap-2 py-2.5 bg-slate-900 text-white rounded-lg text-sm font-semibold hover:bg-slate-800 transition-colors disabled:opacity-50"
          >
            {isExporting === 'PDF' ? <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> : <Download className="w-4 h-4" />}
            Generate PDF
          </button>
        </div>

        {/* Excel Export */}
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 flex flex-col items-center text-center hover:border-emerald-300 transition-colors">
          <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center mb-4">
            <FileSpreadsheet className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800 text-lg mb-2">Excel Workbook</h3>
          <p className="text-xs text-slate-500 mb-6 flex-1">Full dataset exported into formatted .xlsx sheets for offline pivot tables.</p>
          <button 
            onClick={exportExcel}
            disabled={isExporting !== null}
            className="w-full flex items-center justify-center gap-2 py-2.5 bg-emerald-600 text-white rounded-lg text-sm font-semibold hover:bg-emerald-700 transition-colors disabled:opacity-50"
          >
            {isExporting === 'EXCEL' ? <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> : <Download className="w-4 h-4" />}
            Export .xlsx
          </button>
        </div>

        {/* CSV Export */}
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 flex flex-col items-center text-center hover:border-emerald-300 transition-colors">
          <div className="w-12 h-12 bg-indigo-50 text-indigo-600 rounded-full flex items-center justify-center mb-4">
            <File className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800 text-lg mb-2">Raw CSV</h3>
          <p className="text-xs text-slate-500 mb-6 flex-1">Comma-separated values ideal for importing into R, Python, or older databases.</p>
          <button 
            onClick={exportCSV}
            disabled={isExporting !== null}
            className="w-full flex items-center justify-center gap-2 py-2.5 bg-white border border-slate-300 text-slate-700 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-colors disabled:opacity-50"
          >
            {isExporting === 'CSV' ? <div className="w-4 h-4 border-2 border-slate-400 border-t-transparent rounded-full animate-spin" /> : <Download className="w-4 h-4" />}
            Export .csv
          </button>
        </div>

        {/* JSON Export */}
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 flex flex-col items-center text-center hover:border-emerald-300 transition-colors">
          <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-full flex items-center justify-center mb-4">
            <FileJson className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-slate-800 text-lg mb-2">JSON Backup</h3>
          <p className="text-xs text-slate-500 mb-6 flex-1">Standardized JSON structure matching the API schema for automated pipelines.</p>
          <button 
            onClick={exportJSON}
            disabled={isExporting !== null}
            className="w-full flex items-center justify-center gap-2 py-2.5 bg-white border border-slate-300 text-slate-700 rounded-lg text-sm font-semibold hover:bg-slate-50 transition-colors disabled:opacity-50"
          >
            {isExporting === 'JSON' ? <div className="w-4 h-4 border-2 border-slate-400 border-t-transparent rounded-full animate-spin" /> : <Download className="w-4 h-4" />}
            Export .json
          </button>
        </div>

      </div>

      <div className="mt-8 bg-slate-50 border border-slate-200 rounded-xl p-6">
        <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2 mb-4">
          <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Compliance Status
        </h3>
        <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
          All exported data adheres to the National Health Data Standards (NHDS) and strips Personal Identifiable Information (PII) to comply with data privacy regulations. Exports are generated locally in the browser context via SheetJS and jsPDF to ensure no sensitive telemetry is transmitted to third-party rendering services.
        </p>
      </div>
    </div>
  );
}
